#!/usr/bin/env bash
# Generate reproducible dependency locks for every deployed service.
#
# The release manifest requires a lock because "fastapi>=0.110.0" does not
# identify what actually ran: a rebuild weeks later resolves to whatever is
# newest, and the study could not then be reproduced from the recorded commit
# alone.
#
# Resolution targets the *container* platform, not the developer machine. The
# images are python:3.12-slim on Linux, so `--python-platform` and
# `--python-version` are pinned to match; resolving on Windows or on a
# different Python would record wheels that production never installs, which
# is worse than no lock because it looks authoritative and is wrong. torch is
# the clearest case -- its Linux and Windows wheels differ.
#
# Editable path installs (`-e ../SharedSchema`) are stripped: SharedSchema is
# vendored from this repository, so the release commit already pins it and a
# resolver cannot express it as a version.
#
# Usage (from the repository root):
#     bash deploy/lock-dependencies.sh
#
# Requires uv (https://docs.astral.sh/uv/). Re-run after editing any
# requirements.txt, and commit the regenerated .lock files.
set -euo pipefail

PYTHON_VERSION="3.12"
PYTHON_PLATFORM="x86_64-unknown-linux-gnu"
SERVICES=(DemoSiteV2 DemoSiteV3 StudyDispatcher CustomerSimulation Experiments)

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

if ! command -v uv >/dev/null 2>&1; then
    echo "error: uv is not installed. See https://docs.astral.sh/uv/" >&2
    exit 1
fi

echo "Locking for Python ${PYTHON_VERSION} on ${PYTHON_PLATFORM} (the container target)."
echo

for service in "${SERVICES[@]}"; do
    src="${service}/requirements.txt"
    out="${service}/requirements.lock"
    if [[ ! -f "$src" ]]; then
        echo "skip ${service}: no requirements.txt"
        continue
    fi

    # Strip editable local path installs; keep everything else verbatim.
    tmp="$(mktemp)"
    grep -vE '^\s*-e\s' "$src" > "$tmp" || true

    if [[ ! -s "$tmp" ]]; then
        echo "skip ${service}: only local editable installs"
        rm -f "$tmp"
        continue
    fi

    echo "==> ${out}"
    uv pip compile "$tmp" \
        --python-version "$PYTHON_VERSION" \
        --python-platform "$PYTHON_PLATFORM" \
        --no-header \
        --quiet \
        --output-file "$out"

    # uv records the stripped temp path in an annotation comment; rewrite it to
    # the real source so the lock says where it came from.
    python - "$out" "$src" <<'PY'
import sys, pathlib, re
lock, source = pathlib.Path(sys.argv[1]), sys.argv[2]
text = lock.read_text(encoding="utf-8")
text = re.sub(r"(?m)^(#\s+via -r ).*$", r"\1" + source, text)
banner = (
    f"# Locked from {source} for Python 3.12 on linux (the container target).\n"
    "# Generated by deploy/lock-dependencies.sh -- do not edit by hand.\n"
    "# Editable local installs (SharedSchema) are pinned by the release commit.\n"
)
lock.write_text(banner + text, encoding="utf-8")
PY

    rm -f "$tmp"
    echo "    $(grep -cE '^[a-zA-Z0-9]' "$out") pinned packages"
done

echo
echo "Done. Commit the .lock files; the release manifest hashes them."
